### ISSUE TITLE
Existing CEF Addon

### ISSUE THREAD

**Issue by ddiakopoulos** [ofZach/ofxCef#1]
https://github.com/ddiakopoulos/ofxCEFClient

**Comment by ofZach** [comment]
thanks!!  I've tried your addon but had trouble getting it to work for me on OSX -- I will give it another shot and report back issues.

**Comment by ddiakopoulos** [comment]
Ahh, you are on OSX! That makes sense. It's for Win only. I was hoping to save someone else the pain. I just read the OF forum post and you've already hit the major issues. The gist of it is that one of the cef examples can be compiled into OF and you draw its offscreen tex to the screen -- but as you noted, offscreen rendering is slow. Here's one of the biggest issues: https://code.google.com/p/chromiumembedded/issues/detail?id=1006

Here's another good post with some of the problems: 
http://coherent-labs.com/blog/what-developers-should-consider-when-using-chromium-embedded-framework-cef-in-their-games/ It's a little FUD about CEF because Coherent is selling a competing framework. The best I can figure about the Coherent UI thing is that they engineered a fork of Chromium directly and put a nice API on top. From what I remember, Awesomium uses CEF with their own hacked texture support.

**Comment by smallfly** [comment]
Thanks for all these helpful informations. I kinda have responded (asking more questions ;) on the OF forum - http://forum.openframeworks.cc/t/using-cef-with-of/18094/16 .

**Comment by ofZach** [comment]
@ddiakopoulos I've made some good progress -- for me, offscreen with the latest CEF binary seems really good and ripping out that offscreen code from cefClient helps alot.  I understand CEF more now, and I think I can fix a few of the issues with your addon (resizing is work for me and text field highlighting, etc).   there's alot of wonkiness still with events (keyboard feels shaky, etc).   Maybe you want to take a look and see if there's some way to merge or some useful elements?    I'll also look and if possible submit a PR....
