### ISSUE TITLE
Turn cefWork into an addon

### ISSUE THREAD

**Issue by smallfly** [ofZach/ofxCef#14]
I would like to start to do some housekeeping and turn this in an addon. How do you think we should proceed?
Should we create it in this repo, in order to keep the history, and then see if we can merge it with ofxCEFClient (link to https://github.com/ofZach/cefWork/issues/1)?

Thanks.

**Comment by ofZach** [comment]
sounds good to me !  let me know if renaming the repo makes sense and will give you admin access in a second if you want to commit directly (otherwise, happy to take PRs)

**Comment by smallfly** [comment]
Great. 

Admin vs PRs is your call. The advantage of PRs, at least a the beginning, is that you will see everything go through and make sure we do this in a way that make sense.

how should we name this addon?

**Comment by smallfly** [comment]
@ofZach This is time to do some refactoring. What name should we pick ofxCEF, ofxChromiumEmbeded, ofxOSRChromiumEmbeded, ofxCEFClient or even something else?

**Comment by ofZach** [comment]
ofxCEF sounds good - we should reach out to the ofxCefClient folks too and see what they want to do

**Comment by smallfly** [comment]
Definitively.

**Comment by smallfly** [comment]
They have just updated the readme for ofxCEFClient though:

> Note This project isn't actively maintained anymore. It still works, but doesn't take advantage of several offscreen rendering enhancements made in the past year to CEF and Chromium. Here is a more recent attempt (OSX).

**Comment by ddiakopoulos** [comment]
If at all possible, it would be nice to merge the two efforts and share a common API. It's just a bit more work since the dependency structure is entirely platform specific. I will be happy to cross-link between the two projects wherever possible (readme, github description etc) in the meanwhile!

**Comment by smallfly** [comment]
The refactoring has started. It's pushed here https://github.com/ofZach/cefWork/tree/refactoring_to_ofxCEF . 

I was going to merge this branch into 'develop', but I have some issues with Git and the CEF Framework. Git says that the files in the framework have been modified, and wont let me reset them. Even after making a 'fake' commit they keep reappearing as modified files. Do you have an idea of what I have broken? 

![repo in SourceTree](http://smallfly.com/of/cef-git.png)

Thanks!

**Comment by ofZach** [comment]
this feels like a line ending thing being applied to binary files wrongly.  I think we should trash .gitattributes, which was solving some other problem you had somewhere with line endings (w/ the shell script maybe?)

**Comment by ofZach** [comment]
changed the name, pulled, seems fine... closing for now
