### ISSUE TITLE
exiting is hard

### ISSUE THREAD

**Issue by ofZach** [ofZach/ofxCef#22]
getting crashed on quiting for the mac.

this info looks useful: 

      After looking at Chromium's code a bit, I think the issue is that, when my app's autorelease pool pops off the stack (at the end of a message loop), it takes with it the one that Chromium created (since it gets created later when initializing CEF). So when CefShutdown is called, Chromium tries to release its autorelease pool, which has already been popped off the stack. Hence the crash.

I will dig into the CEF code and see if there's some potential fix, I've tried unwinding piece by piece, with some error handling internally but I still get a crash: 

    if (key == ' '){
        cefgui->renderHandler->bIsShuttingDown = true;
        cefgui->browser->GetHost()->CloseBrowser(false);
    }
    
    if (key == 't'){
        cefgui->disableEvents();
        delete cefgui;
        cefgui = NULL;
    }
    
    if (key == 'y'){
        CefShutdown();
    }

but I still get the dreaded autoreleasepool error.

**Comment by ofZach** [comment]
ok here's the trick: 

a) CefInitialize *has* to be called before a window is setup -- we need to separate out that from the OF specific stuff like registering to events
b)  shutdown seems to be a multi step process like closing windows then deleting cefGui...  some stuff needs to know it's in the process of shutting down

    void ofApp::exit()
    {
        
        cefgui->renderHandler->bIsShuttingDown = true;
        cefgui->browser->GetHost()->CloseBrowser(false);
        cefgui->disableEvents();
        delete cefgui;
        cefgui = NULL;
        
    }

c) cefShutdown doesn't seem to work well -- I feel like it wants to own the shutdown process of the main app and is kind of convoluted.  I can't do it without some sort of crash.

**Comment by smallfly** [comment]
I had to do the a) ("CefInitialize has to be called before a window is setup") in order to make CEF run on Windows (see #23).

**Comment by ofZach** [comment]
I've found that doing this has some drawbacks -- webgl doesn't seem to work on osx and overall performance is much worse...   still investigating.

**Comment by ofZach** [comment]
it looks like we are loosing some helpers (the gpu helper in particular) due to the dylibs messing up.  

dyld: Library not loaded: ./libfmodex.dylib
  Referenced from: /Users/zachlieberman/Documents/projects/OF/of_v0.8.4_osx_release/addons/ofxCef/example-ofxCEF/bin/example-ofxCEFDebug.app/Contents/Frameworks/example-ofxCEFDebug Helper.app/Contents/MacOS/example-ofxCEFDebug Helper
  Reason: image not found

working on fixes for if we start this way (ie CEF starts before everything)

**Comment by ofZach** [comment]
ps: I've found it helpful to put debug information into the helper processes, ie spit out the argc / argv: 

    printf("%i \n", argc);
    for (int i = 0; i < argc; i++){
        printf("%s \n", argv[i]);
    }
    

for example you can see things like: 

--type=renderer 
--enable-deferred-image-decoding 
    --lang=en-US 
    --lang=en-US 
    --enable-delegated-renderer 
    --enable-impl-side-painting 
    --num-raster-threads=1 
    --disable-accelerated-video-decode 
     --channel=36482.1.712723893

**Comment by ofZach** [comment]
ok!  we can get performance back on OSX if we init CEF before OF, make sure all the helpers have dynamic linking right.   I guess the linking wasn't 100% right before, but because libfmod was already loaded somewhere earlier, the helpers were ok?   In this case, I've found it useful to do the install_name_tool stuff after the make more helpers script, which I think was kind of clobbering things.

**Comment by ofZach** [comment]
pushed changes that should help on OSX -- closing this for now....
