### ISSUE TITLE
Issues compiling (fixed - pull request sent) and running (help needed) on OSX 10.10, ofx 0.8.4

### ISSUE THREAD

**Issue by sheridanis** [ofZach/ofxCef#25]
Hi Guys,

I just grabbed the latest version of the repo and when I went to compile I was getting an error with a missing file in one of the run scripts in the build phase.   I updated the file name and it compiles fine now (I've sent a pull request) but I'm just seeing a white screen once things load and am not sure why.....well I think I know why but am not sure how to fix it.   In the console I'm seeing
```
dyld: Library not loaded: @executable_path/../../../../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Users/jrs/Code/openframeworks/of_v0.8.4_osx_release/addons/ofxCef/example-ofxCEF/bin/example-ofxCEFDebug.app/Contents/Frameworks/example-ofxCEFDebug Helper.app/Contents/MacOS/example-ofxCEFDebug Helper
?  Reason: Incompatible library version: example-ofxCEFDebug Helper requires version 31979.8.123 or later, but Chromium Embedded Framework provides version 31949.8.123
Reshape: 5600 - 3400
```
But the framework is included in the repo so it should be the right version no?

What dev environment are you guys using? I'm running osx 10.10, ofx 0.8.4 and xcode6.2.   I notice on the https://cefbuilds.com/ site their not supporting 32 bit anymore - are you guys developing with 64 bit on the master branch of ofx?

Any help would be much appreciated - James

I'm running osx 10.10, ofx 0.8.4 and xcode 6.2

**Comment by ofZach** [comment]
can you try this again?   I have fixed some of the scripts which should help....

**Comment by ofZach** [comment]
we are using this version (from cef_version.h)

#define CEF_VERSION_MAJOR 3
#define CEF_REVISION 1949
#define COPYRIGHT_YEAR 2014
#define CHROME_VERSION_MAJOR 39
#define CHROME_VERSION_MINOR 0
#define CHROME_VERSION_BUILD 2171
#define CHROME_VERSION_PATCH 65

**Comment by sheridanis** [comment]
Sorry only just noticed you'd replied

I just got a fresh copy of the repo but now I get

```
ld: library not found for -lcef_dll_wrapper
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sheridanis** [comment]
To fix this I just grabbed the lib from the last commit on the 10th april - 494bcd38e1617fb6bf1226a8f5d31ffd0a87882c [494bcd3]

and now all is good
